#!/usr/bin/env bash
# configure haproxy
sudo apt update -y
sudo apt install haproxy -y
config=\
"backend my_servers
        balance roundrobin
        server 5420-web-01 54.235.49.27:80
        server 5420-web-02 52.90.96.180:80
frontend haproxy_inbound
        bind *:80
        default_backend my_servers
        mode http
"

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start